# name of the software
name: Gtk Theming Guide
# current version of the software
version: 1.0.0
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon: png

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
# download:
#   popup: false
#   url: #
  #https://github.com/mistic100/jekyll-bootstrap-doc/archive/gh-pages.zip
  # bower: jekyll-bootstrap-doc
  # npm: jekyll-bootstrap-doc
  # cdn:
  #   url: https://cdnjs.com/libraries/jekyll-bootstrap-doc
  #   img: https://alemangui.github.io/pizzicato/img/cdnjs.svg
  #   name: cdnjs

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://surajmandalcell.github.io/Gtk-Theming-Guide/

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://surajmandalcell.github.io/Gtk-Theming-Guide/
  - title: Issues
    url: https://surajmandalcell.github.io/Gtk-Theming-Guide/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: surajmandalcell
  repo: Gtk-Theming-Guide

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl: https://facebook.com/suraj.mandalcell


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
